In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
mouse_drug_data_to_load = './data/mouse_drug_data.csv'
clinical_trial_data_to_load = './data/clinicaltrial_data.csv'

# Read the Mouse and Drug Data and the Clinical Trial Data
mouse_drug_data = pd.read_csv("data/mouse_drug_data.csv")
clinical_trial_data = pd.read_csv("data/clinicaltrial_data.csv")

# Combine the data into a single dataset
combined_data = pd.merge(mouse_drug_data, clinical_trial_data, on="Mouse ID", how = "left")

# Display the data table for preview
combined_data.head()

  Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     f234  Stelasyn          0           45.000000                 0
1     f234  Stelasyn          5           47.313491                 0
2     f234  Stelasyn         10           47.904324                 0
3     f234  Stelasyn         15           48.735197                 1
4     f234  Stelasyn         20           51.112713                 2

## Tumor Response to Treatment

In [2]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 
tumor_volume = combined_data.groupby(["Drug", "Timepoint"])
mean_tumor = tumor_volume["Tumor Volume (mm3)"].mean()
mean_tumor

# Convert to DataFrame
tumor_response = pd.DataFrame(mean_tumor).reset_index()

# Preview DataFrame
tumor_response.head()

        Drug  Timepoint  Tumor Volume (mm3)
0  Capomulin          0           45.000000
1  Capomulin          5           44.266086
2  Capomulin         10           43.084291
3  Capomulin         15           42.064317
4  Capomulin         20           40.716325

In [3]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint
tumor_volume_error = tumor_volume["Tumor Volume (mm3)"].sem()

# Convert to DataFrame
tumor_response_error = pd.DataFrame(tumor_volume_error).reset_index()

# Preview DataFrame
tumor_response_error.head()

        Drug  Timepoint  Tumor Volume (mm3)
0  Capomulin          0            0.000000
1  Capomulin          5            0.448593
2  Capomulin         10            0.702684
3  Capomulin         15            0.838617
4  Capomulin         20            0.909731

In [4]:
# Minor Data Munging to Re-Format the Data Frames
data_munging = tumor_response.pivot(index = 'Timepoint', columns = 'Drug', values = 'Tumor Volume (mm3)')

# Preview that Reformatting worked
data_munging

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
5,44.266086,46.503051,47.062001,47.389175,46.796098,47.125589,47.248967,43.944859,47.527452,46.851818
10,43.084291,48.285125,49.403909,49.582269,48.694210,49.423329,49.101541,42.531957,49.463844,48.689881
15,42.064317,50.094055,51.296397,52.399974,50.933018,51.359742,51.067318,41.495061,51.529409,50.779059
20,40.716325,52.157049,53.197691,54.920935,53.644087,54.364417,53.346737,40.238325,54.067395,53.170334
25,39.939528,54.287674,55.715252,57.678982,56.731968,57.482574,55.504138,38.974300,56.166123,55.432935
30,38.769339,56.769517,58.299397,60.994507,59.559509,59.809063,58.196374,38.703137,59.826738,57.713531
35,37.816839,58.827548,60.742461,63.371686,62.685087,62.420615,60.350199,37.451996,62.440699,60.089372
40,36.958001,61.467895,63.162824,66.068580,65.600754,65.052675,63.045537,36.574081,65.356386,62.916692
45,36.236114,64.132421,65.755562,70.662958,69.265506,68.084082,66.258529,34.955595,68.438310,65.960888

In [5]:
# Generate the Plot (with Error Bars)
#capomulin_error = tumor_response_error.loc[tumor_response_error["Drug"] == "Capomulin", "Tumor Volume (mm3)"]
#infubinol_error = tumor_response_error.loc[tumor_response_error["Drug"] == "Infubinol", "Tumor Volume (mm3)"]
#ketapril_error = tumor_response_error.loc[tumor_response_error["Drug"] == "Ketapril", "Tumor Volume (mm3)"]
#placebo_error = tumor_response_error.loc[tumor_response_error["Drug"] == "Placebo", "Tumor Volume (mm3)"]
#time = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

#plt.errorbar("Time", data_munging["Capomulin"] , yerr= capomulin_error, label= "Capomulin", marker= "o", color="red", linestyle='--')
#plt.errorbar("Time", data_munging["Infubinol"] , yerr= infubinol_error, label= "Infubinol", marker= "^", color="blue", linestyle='--')
#plt.errorbar("Time", data_munging["Ketapril"] , yerr= ketapril_error, label= "Ketapril", marker= "D", color="black", linestyle='--')
#plt.errorbar("Time", data_munging["Placebo"] , yerr= placebo_error , label= "Placebo", marker= "s", color="green", linestyle='--')
#plt.legend()
#plt.title("Tumor Response to Treatment ")
#plt.xlabel("Time (Days)")
#plt.ylabel("Tumor Volume (mm3)")
#plt.grid()
# Save the Figure
#plt.savefig("Images/Tumor_Response.png")

In [6]:
# Show the Figure
#plt.show()

![Tumor Response to Treatment](../Images/treatment.png)

## Metastatic Response to Treatment

In [7]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 
tumor_volume = combined_data.groupby(["Drug", "Timepoint"])
mean_met_data = tumor_volume["Metastatic Sites"].mean()

# Convert to DataFrame
mean_met_data = pd.DataFrame(mean_met_data).reset_index()

# Preview DataFrame
mean_met_data.head()

        Drug  Timepoint  Metastatic Sites
0  Capomulin          0          0.000000
1  Capomulin          5          0.160000
2  Capomulin         10          0.320000
3  Capomulin         15          0.375000
4  Capomulin         20          0.652174

In [8]:
# Store the Standard Error associated with Met. Sites Grouped by Drug and Timepoint 
met_sites_error = tumor_volume["Metastatic Sites"].sem()

# Convert to DataFrame
met_data_error = pd.DataFrame(met_sites_error).reset_index()

# Preview DataFrame
met_data_error.head()

        Drug  Timepoint  Metastatic Sites
0  Capomulin          0          0.000000
1  Capomulin          5          0.074833
2  Capomulin         10          0.125433
3  Capomulin         15          0.132048
4  Capomulin         20          0.161621

In [9]:
# Minor Data Munging to Re-Format the Data Frames
data_munging_met = mean_met_data.pivot(index = 'Timepoint', columns = 'Drug', values = 'Metastatic Sites')

# Preview that Reformatting worked
data_munging_met.head()

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.160000,0.380952,0.280000,0.304348,0.260870,0.375000,0.320000,0.120000,0.240000,0.166667
10,0.320000,0.600000,0.666667,0.590909,0.523810,0.833333,0.565217,0.250000,0.478261,0.500000
15,0.375000,0.789474,0.904762,0.842105,0.857143,1.250000,0.764706,0.333333,0.782609,0.809524
20,0.652174,1.111111,1.050000,1.210526,1.150000,1.526316,1.000000,0.347826,0.952381,1.294118

In [10]:
# Generate the Plot (with Error Bars)

# Save the Figure

# Show the Figure

![Metastatic Spread During Treatment](../Images/spread.png)

## Survival Rates

In [11]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)
tumor_volume = combined_data.groupby(["Drug", "Timepoint"])
mouse_count = tumor_volume["Mouse ID"].count()

# Convert to DataFrame
mouse_data = pd.DataFrame(mouse_count).reset_index()

# Preview DataFrame
mouse_data.head()

        Drug  Timepoint  Mouse ID
0  Capomulin          0        25
1  Capomulin          5        25
2  Capomulin         10        25
3  Capomulin         15        24
4  Capomulin         20        23

In [12]:
# Minor Data Munging to Re-Format the Data Frames
mouse_data_munging = mouse_data.pivot(index = 'Timepoint',columns ='Drug', values = 'Mouse ID')

# Preview the Data Frame
mouse_data_munging

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,25,25,25,25,25,25,26,25,26,25
5,25,21,25,23,23,24,25,25,25,24
10,25,20,21,22,21,24,23,24,23,22
15,24,19,21,19,21,20,17,24,23,21
20,23,18,20,19,20,19,17,23,21,17
25,22,18,18,19,18,17,14,23,19,16
30,22,16,17,18,15,15,13,23,18,15
35,22,14,12,17,15,14,10,21,16,14
40,21,14,10,15,15,12,9,20,12,14
45,21,13,9,11,13,11,7,20,11,14

In [13]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/survival.png)

## Summary Bar Graph

In [14]:
# Calculate the percent changes for each drug
tumor_volume_before = 45
tumor_change = ((data_munging.loc[45, :] - tumor_volume_before)/tumor_volume_before)*100

# Display the data to confirm
tumor_change

Drug
Capomulin   -19.475303
Ceftamin     42.516492
Infubinol    46.123472
Ketapril     57.028795
Naftisol     53.923347
Placebo      51.297960
Propriva     47.241175
Ramicane    -22.320900
Stelasyn     52.085134
Zoniferol    46.579751
Name: 45, dtype: float64

In [16]:
# Store all Relevant Percent Changes into a Tuple
tuple_changes = tuple(zip(tumor_change.index, tumor_change))
tuple_changes_list = list(tuple_changes)
tuple_changes_list

# Splice the data between passing and failing drugs
passing_drugs = []
failing_drugs = []
passing_drugs_index = []
failing_drugs_index = []
for x,elements in tuple_changes_list :
    if elements > 0 :
        passing_drug = elements
        passing_drugs.append(elements)
        passing_drugs_index.append(j)
    else :
        failing_drugs = elements
        failing_drugs.append(elements)
        failing_drugs_index.append(j)
passing_drugs = list(zip(passing_drugs_index, passing_drugs))
failing_drugs = list(zip(failing_drugs_index, failing_drugs))

# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
#fig.show()

AttributeError: 'float' object has no attribute 'append'

![Metastatic Spread During Treatment](../Images/change.png)